version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php5.4
      - php7.3
      - php7.4
      - php8.1

  php5.4:
    image: php:5.4-fpm
    ports:
    - '5400:80'
    expose:
    - '5400'
    volumes:
      - ./php5.4:/var/www/html
      - ./logs/php5.4:/var/log/php
      - ./php/5.4/php.ini:/usr/local/etc/php/php.ini
      - ./php/5.4/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php7.3:
    image: php:7.3-fpm
    ports:
    - '7300:80'
    expose:
    - '7300'
    volumes:
      - ./php7.3:/var/www/html
      - ./logs/php7.3:/var/log/php
      - ./php/7.3/php.ini:/usr/local/etc/php/php.ini
      - ./php/7.3/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php7.4:
    image: php:7.4-fpm
    ports:
    - '7400:80'
    expose:
    - '7400'
    volumes:
      - ./php7.4:/var/www/html
      - ./logs/php7.4:/var/log/php
      - ./php/7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php/7.4/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php8.1:
    image: php:8.1-fpm
    ports:
    - '8100:80'
    expose:
    - '8100'
    volumes:
      - ./php8.1:/var/www/html
      - ./logs/php8.1:/var/log/php
      - ./php/8.1/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/8.1/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./scripts:/docker-entrypoint-initdb.d
